### ISSUE TITLE
Bargraph

### ISSUE THREAD

**Issue by girikumarkolla** [itaidagan/FranchiseRevenueComparison#2]
is it possible to draw in bar graph

**Comment by itaidagan** [comment]
Probably, but then much of the code becomes irrelevant. 
You'd need to change the main plot from a line plot to a bar plot (line 105 in FranchiseAnimation.py) and then get rid of a lot of unnecessary code. If no additional coding is done I guess that the order of the franchises will stay static. If you'd like to change that - you'd have to adjust it yourself.
